version: '3.8'

services:
  app:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - .:/app
      - ./logs:/app/logs
      - ./reports:/app/reports
      - ./config:/app/config
      - ./output:/app/output
    environment:
      - PYTHONUNBUFFERED=1
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - FIRECRAWL_API_URL=https://j12d832.impossible.finance
      - REDIS_URL=redis://redis:6379
      - APP_ENV=${APP_ENV:-development}
      - DEBUG=${DEBUG:-true}
      - LOG_LEVEL=${LOG_LEVEL:-debug}
      - OUTPUT_FORMAT=${OUTPUT_FORMAT:-markdown}
      - MAX_REQUESTS_PER_HOUR=${MAX_REQUESTS_PER_HOUR:-100}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501"]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      - redis
    # If on Linux, you might need to add extra_hosts for host.docker.internal:
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  redis_data: 